"""
init

Revision ID: 22dbd57d8271
Revises: None
Create Date: 2014-09-03 16:50:14.740000

"""

# revision identifiers, used by Alembic.
revision = '22dbd57d8271'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
