"""
1.1

Revision ID: a35c7dbf502
Revises: 4bf22f29acfa
Create Date: 2014-09-27 19:22:01.552000

"""

# revision identifiers, used by Alembic.
revision = 'a35c7dbf502'
down_revision = '4bf22f29acfa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarmobjects', sa.Column('active', sa.Integer(), nullable=True))
    op.add_column('alarmobjects', sa.Column('attributes', sa.Text(), nullable=True))
    op.add_column('alarmobjects', sa.Column('bma', sa.String(length=10), nullable=True))
    op.add_column('alarmobjects', sa.Column('typeid', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarmobjects', 'typeid')
    op.drop_column('alarmobjects', 'bma')
    op.drop_column('alarmobjects', 'attributes')
    op.drop_column('alarmobjects', 'active')
    ### end Alembic commands ###
